name: "Create Releases"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: 'Install OptiPNG'
        run: sudo apt-get install -y optipng

      - name: 'Optimize Images'
        run: |
          find . -name "*.png" -exec optipng -o9 {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build Modpack
        run: 'chmod +x ./gradlew && ./gradlew buildTargets'

      - name: Generate changelog
        run: 'python scripts/changelogger.py'

      - name: Upload Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 3HsvIkiC
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ""
          modrinth-files:
            - build/target/*.mrpack
          github-files:
            - build/target/*.mrpack
            - build/target/*.zip
          loaders:
            - forge
          game-versions:
            - 1.20.1
          version-type: beta

          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: changelog.md
          github-generate-changelog: true
