name: "Upload new version to Modrinth"

on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: robinraju/release-downloader@v1.10
        with:
          fileName: '*.mrpack'
          out-file-path: downloaded_release
          releaseId: ${{ github.event.release.id }}
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 3HsvIkiC
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          name: ""
          files:
            - downloaded_release/*.mrpack
          loaders:
            - forge
          game-versions:
            - 1.20.1
          version-type: beta
