name: "Test something"

on:
  push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build CurseForge pack
        run: 'chmod +x ./gradlew && ./gradlew buildCursePack'

      - name: Generate changelog ;)
        run: 'python scripts/changelogger.py'

      - name: List all files
        run: 'python scripts/list_all_files.py'
